wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702675768.12627
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.11.5
      5: 0.16.1
      8:
      - 3
      - 5
      13: windows-amd64
